# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_eOLqmFF5iijBS0CXYQVl6Q9Wgjzm3_
"""



"""# 1.**List**"""

#list of integer value
a=[1,2,3,4,5,6,7,8,9,10]
print('original List',a)
#2 Find sum,max,min
print('sum',sum(a))
print('max',max(a))
print('min',min(a))

#3 add new Element and remove

a.append(11)
print('add in List',a)

a.remove(5)
print('remove in List',a)

#4print new List
print('original List',a)

#5 sort th list in ascending and decending order
print('sort array in assending',sorted(a))
print('decending array',sorted(a,reverse=True))

"""# 2. **Tuples**"""

#1 create a tuple with 5 Strings
fruits=('Apple','Mango','Banana','orange','watermelon')

#print 2 and 4 element
print('',fruits[2])
print('',fruits[4])

#3. Try to modify an element and the error
# fruits.append('grapes')
# fruits.remove('Apple')

#convert the tiple into list and them modify it
fruit_list=list(fruits)
fruit_list[2]='Grapes'
print("Modified List",fruit_list)

"""# 3. **Sets**"""

#1 create two sets with  some common and unique elements

a = {1, 2, 3, 4, 5}
b = {1,2,3,4, 9, 6, 7, 8}
print('a sets',a)
print('b sets',b)

#2 perform unions ,intesection,and diff operations
print('Union',a|b)
print('Intersection',a & b)
print('Difference (a - b):', a - b)

"""# 4. **Dictionaries**"""

#create dictionary
students={'ali':1,'sardar':2,'saif':3}

#PRINT keys and values

print('keys',students.keys())
print('values',students.values)

#values updated
print('updated dictionary',students)